### ISSUE TITLE
Error in Console - Your Mod?

### ISSUE THREAD

**Issue by djdanby** [derfl007/df-roads#6]
Is this from your mod?

`[01:13:34] [Server thread/ERROR] [FML]: Parsing error loading recipe df-roads:road_slope
com.google.gson.JsonSyntaxException: Unknown item 'df-roads:road_slope'
	at net.minecraftforge.common.crafting.CraftingHelper.getItemStack(CraftingHelper.java:211) ~[CraftingHelper.class:?]
	at net.minecraftforge.common.crafting.CraftingHelper.lambda$init$14(CraftingHelper.java:515) ~[CraftingHelper.class:?]
	at net.minecraftforge.common.crafting.CraftingHelper.getRecipe(CraftingHelper.java:408) ~[CraftingHelper.class:?]
	at net.minecraftforge.common.crafting.CraftingHelper.lambda$loadRecipes$22(CraftingHelper.java:710) ~[CraftingHelper.class:?]
	at net.minecraftforge.common.crafting.CraftingHelper.findFiles(CraftingHelper.java:821) ~[CraftingHelper.class:?]
	at net.minecraftforge.common.crafting.CraftingHelper.loadRecipes(CraftingHelper.java:667) ~[CraftingHelper.class:?]
	at java.util.ArrayList.forEach(Unknown Source) [?:1.8.0_171]
	at net.minecraftforge.common.crafting.CraftingHelper.loadRecipes(CraftingHelper.java:619) [CraftingHelper.class:?]
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:718) [Loader.class:?]
	at net.minecraftforge.fml.server.FMLServerHandler.finishServerLoading(FMLServerHandler.java:107) [FMLServerHandler.class:?]
	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStarted(FMLCommonHandler.java:337) [FMLCommonHandler.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:219) [nz.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:484) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_171]`

I use an SpongeForge 1566 Server in Version 1.12.2

**Comment by derfl007** [comment]
Uh yeah it seems to be, does this cause any problems for you? If so, I'll try to fix it ASAP. I think it might be a problem with all the old files that I haven't deleted yet

**Comment by djdanby** [comment]
Currently I could not find any errors in the game. I just do not want to have any errors in the console, because otherwise I could overlook important error messages. ;)

**Comment by derfl007** [comment]
I'll try to fix any console errors in the next update, sorry for the late response
